## Ocean plastic pollution

Below we read in the datasets and do preliminary analysis

In [1]:
import pandas as pd
import numpy as np
import plotly
from plotly import tools
plotly.offline.init_notebook_mode(connected=True)

from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
import plotly.io as pio
pd.set_option('display.max_columns', 500)

In [2]:
#Read in the stats for plastic removal at different places:
cost_df = pd.read_csv('../data/cost_where.csv')
cost_df['mid_point'] = (cost_df.ul+cost_df.ll)/2.0
cost_df['range'] = (cost_df.ul - cost_df.ll)/2.0
cost_df.tail()

   loc_        where    ll    ul  mid_point   range
0     0     Open sea  4000  6000     5000.0  1000.0
1     1  Near harbor  1000  1082     1041.0    41.0
2     2      On land    20   300      160.0   140.0

In [3]:
#Amount of plastic removed per USD1000:
cost_inv = pd.read_csv('../data/cost_inverted.csv')
cost_inv.tail()

   loc_                    where  ton_removed
0     0                 Open sea          0.2
1     1              Near harbor          1.0
2     2    High-income countries          4.8
3     3  Middle-income countries          9.5
4     4     Low-income countries         20.0

In [4]:
#read in world bank data on countries:
country_df = pd.read_csv('../data/country_level_data_0.csv')
country_df['gdp_per_capita'] = country_df.gdp/country_df.population_population_number_of_people
country_df.tail()

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent,other_information_information_system_for_solid_waste_management,other_information_national_agency_to_enforce_solid_waste_laws_and_regulations,other_information_national_law_governing_solid_waste_management_in_the_country,other_information_ppp_rules_and_regulations,other_information_summary_of_key_solid_waste_information_made_available_to_the_public,population_population_number_of_people,special_waste_agricultural_waste_tons_year,special_waste_construction_and_demolition_waste_tons_year,special_waste_e_waste_tons_year,special_waste_hazardous_waste_tons_year,special_waste_industrial_waste_tons_year,special_waste_medical_waste_tons_year,total_msw_total_msw_generated_tons_year,waste_collection_coverage_rural_percent_of_geographic_area,waste_collection_coverage_rural_percent_of_households,waste_collection_coverage_rural_percent_of_population,waste_collection_coverage_rural_percent_of_waste,waste_collection_coverage_total_percent_of_geographic_area,waste_collection_coverage_total_percent_of_households,waste_collection_coverage_total_percent_of_population,waste_collection_coverage_total_percent_of_waste,waste_collection_coverage_urban_percent_of_geographic_area,waste_collection_coverage_urban_percent_of_households,waste_collection_coverage_urban_percent_of_population,waste_collection_coverage_urban_percent_of_waste,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured,gdp_per_capita
212,XKX,ECS,Kosovo,LMC,7.129272e+09,42.000000,6.000000,6.000000,20.000000,8.000000,11.000000,NaN,7.0,NaN,Yes,Yes,Yes,Yes,NaN,1801800.00,3880.0,217241.0,23.0,495.0,NaN,834.0,319000.0,NaN,NaN,35.0,NaN,NaN,NaN,39.0,NaN,NaN,NaN,100.0,NaN,NaN,NaN,66.43,NaN,NaN,33.57,NaN,NaN,NaN,NaN,NaN,NaN,3956.749801
213,YEM,MEA,"Yemen, Rep.",LIC,1.192703e+10,65.000000,1.000000,6.000000,6.000000,7.000000,10.000000,1.0,3.0,1.0,No,Yes,Yes,No,NaN,27584213.00,NaN,NaN,42000.0,21000.0,NaN,NaN,4836820.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,NaN,NaN,25.00,NaN,8.0,NaN,47.0,8.0,Other,432.386104
214,ZAF,SSF,South Africa,UMC,4.212087e+11,16.381655,5.200216,16.910461,45.020646,9.396918,7.090104,NaN,NaN,NaN,Yes,Yes,Yes,NaN,NaN,51729345.36,NaN,NaN,321000.0,1319096.0,NaN,NaN,18457232.0,NaN,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,90.5,NaN,NaN,NaN,NaN,72.00,NaN,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,8142.547711
215,ZMB,SSF,Zambia,LMC,2.703717e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,14264756.00,NaN,NaN,15000.0,80000.0,NaN,NaN,2608268.0,NaN,NaN,NaN,NaN,NaN,10.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1895.382458
216,ZWE,SSF,Zimbabwe,LIC,1.481899e+10,36.000000,5.000000,6.000000,3.000000,27.000000,23.000000,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,12500525.00,NaN,NaN,13000.0,37346.0,NaN,NaN,1449752.0,NaN,NaN,NaN,NaN,NaN,63.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,NaN,84.0,NaN,NaN,1185.469109

In [9]:
#introduce income-id number and combine LMC and UMC as MIC:
def income_id_num(row):
    if row['income_id'] == 'HIC':
        return 3
    elif row['income_id'] == 'UMC' or row['income_id'] == 'LMC':
        return 2
    elif row['income_id'] == 'LIC':
        return 1
    else:
        return 0
    
country_df['income_id_num'] = country_df.apply(income_id_num, axis=1)
country_df.tail()

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent,other_information_information_system_for_solid_waste_management,other_information_national_agency_to_enforce_solid_waste_laws_and_regulations,other_information_national_law_governing_solid_waste_management_in_the_country,other_information_ppp_rules_and_regulations,other_information_summary_of_key_solid_waste_information_made_available_to_the_public,population_population_number_of_people,special_waste_agricultural_waste_tons_year,special_waste_construction_and_demolition_waste_tons_year,special_waste_e_waste_tons_year,special_waste_hazardous_waste_tons_year,special_waste_industrial_waste_tons_year,special_waste_medical_waste_tons_year,total_msw_total_msw_generated_tons_year,waste_collection_coverage_rural_percent_of_geographic_area,waste_collection_coverage_rural_percent_of_households,waste_collection_coverage_rural_percent_of_population,waste_collection_coverage_rural_percent_of_waste,waste_collection_coverage_total_percent_of_geographic_area,waste_collection_coverage_total_percent_of_households,waste_collection_coverage_total_percent_of_population,waste_collection_coverage_total_percent_of_waste,waste_collection_coverage_urban_percent_of_geographic_area,waste_collection_coverage_urban_percent_of_households,waste_collection_coverage_urban_percent_of_population,waste_collection_coverage_urban_percent_of_waste,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured,gdp_per_capita,income_id_num
212,XKX,ECS,Kosovo,LMC,7.129272e+09,42.000000,6.000000,6.000000,20.000000,8.000000,11.000000,NaN,7.0,NaN,Yes,Yes,Yes,Yes,NaN,1801800.00,3880.0,217241.0,23.0,495.0,NaN,834.0,319000.0,NaN,NaN,35.0,NaN,NaN,NaN,39.0,NaN,NaN,NaN,100.0,NaN,NaN,NaN,66.43,NaN,NaN,33.57,NaN,NaN,NaN,NaN,NaN,NaN,3956.749801,2
213,YEM,MEA,"Yemen, Rep.",LIC,1.192703e+10,65.000000,1.000000,6.000000,6.000000,7.000000,10.000000,1.0,3.0,1.0,No,Yes,Yes,No,NaN,27584213.00,NaN,NaN,42000.0,21000.0,NaN,NaN,4836820.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,NaN,NaN,25.00,NaN,8.0,NaN,47.0,8.0,Other,432.386104,1
214,ZAF,SSF,South Africa,UMC,4.212087e+11,16.381655,5.200216,16.910461,45.020646,9.396918,7.090104,NaN,NaN,NaN,Yes,Yes,Yes,NaN,NaN,51729345.36,NaN,NaN,321000.0,1319096.0,NaN,NaN,18457232.0,NaN,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,90.5,NaN,NaN,NaN,NaN,72.00,NaN,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,8142.547711,2
215,ZMB,SSF,Zambia,LMC,2.703717e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,14264756.00,NaN,NaN,15000.0,80000.0,NaN,NaN,2608268.0,NaN,NaN,NaN,NaN,NaN,10.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1895.382458,2
216,ZWE,SSF,Zimbabwe,LIC,1.481899e+10,36.000000,5.000000,6.000000,3.000000,27.000000,23.000000,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,12500525.00,NaN,NaN,13000.0,37346.0,NaN,NaN,1449752.0,NaN,NaN,NaN,NaN,NaN,63.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,NaN,84.0,NaN,NaN,1185.469109,1

In [5]:
#inadequately managed plastic for different countries, from Jambeck 2015
inad_waste = pd.read_csv('../data/inadequately-managed-plastic.csv')
inad_waste.tail()

        Entity Code  Year  pct_inadeq_plastic_waste
181    Uruguay  URY  2010                         8
182    Vanuatu  VUT  2010                        81
183  Venezuela  VEN  2010                         5
184    Vietnam  VNM  2010                        86
185      Yemen  YEM  2010                        73

In [11]:
inad_income_level = inad_waste.merge(country_df[['iso3c','income_id_num','income_id','gdp_per_capita',
                                                 'population_population_number_of_people']],
                                    left_on='Code',right_on='iso3c',how='left')


inad_income_level['pop_times_pct_iwaste'] = (inad_income_level.population_population_number_of_people*\
                                             inad_income_level.pct_inadeq_plastic_waste)
inad_income_level.tail()

,Entity,Code,Year,pct_inadeq_plastic_waste,iso3c,income_id_num,income_id,gdp_per_capita,population_population_number_of_people,pop_times_pct_iwaste
181,Uruguay,URY,2010,8,URY,3.0,HIC,14093.603406,3431552.0,2.745242e+07
182,Vanuatu,VUT,2010,81,VUT,2.0,LMC,2873.692937,270402.0,2.190256e+07
183,Venezuela,VEN,2010,5,VEN,2.0,UMC,NaN,29893080.0,1.494654e+08
184,Vietnam,VNM,2010,86,VNM,2.0,LMC,1887.727320,86932500.0,7.476195e+09
185,Yemen,YEM,2010,73,YEM,1.0,LIC,432.386104,27584213.0,2.013648e+09

In [12]:

inad_income_level_grouped = inad_income_level.groupby('income_id_num').agg({'pop_times_pct_iwaste':'sum',
                                                        'population_population_number_of_people':'sum'})

inad_income_level_grouped['pct_inadeq_managed'] = (inad_income_level_grouped['pop_times_pct_iwaste']/\
                                inad_income_level_grouped['population_population_number_of_people'])

inad_income_level_grouped

,pop_times_pct_iwaste,population_population_number_of_people,pct_inadeq_managed
income_id_num,,,
1.0,2.471727e+10,3.070820e+08,80.490799
2.0,3.371164e+11,4.965333e+09,67.894023
3.0,1.628403e+09,1.185157e+09,1.373998

In [8]:
#waste generate per person per day for different countries, from Jambeck 2015
ppd_waste = pd.read_csv('../data/plastic-waste-per-capita.csv')
ppd_waste.tail()

        Entity Code  Year  waste_plastic_kgppd
181    Uruguay  URY  2010                0.252
182    Vanuatu  VUT  2010                0.295
183  Venezuela  VEN  2010                0.252
184    Vietnam  VNM  2010                0.103
185      Yemen  YEM  2010                0.103

In [13]:
ppd_income_level = ppd_waste.merge(country_df[['iso3c','income_id_num','income_id','gdp_per_capita',
                                                 'population_population_number_of_people']],
                                    left_on='Code',right_on='iso3c',how='left')
ppd_income_level[(ppd_income_level.gdp_per_capita>=40000) & 
                 (ppd_income_level.gdp_per_capita<1000000)].sort_values(by='waste_plastic_kgppd')
ppd_income_level['eq_bottle_wt'] = ppd_income_level.waste_plastic_kgppd/0.0095
ppd_income_level['total_plastic_pd'] = (ppd_income_level.waste_plastic_kgppd*\
                                        ppd_income_level.population_population_number_of_people)
ppd_income_level.tail()

,Entity,Code,Year,waste_plastic_kgppd,iso3c,income_id_num,income_id,gdp_per_capita,population_population_number_of_people,eq_bottle_wt,total_plastic_pd
181,Uruguay,URY,2010,0.252,URY,3.0,HIC,14093.603406,3431552.0,26.526316,864751.104
182,Vanuatu,VUT,2010,0.295,VUT,2.0,LMC,2873.692937,270402.0,31.052632,79768.590
183,Venezuela,VEN,2010,0.252,VEN,2.0,UMC,NaN,29893080.0,26.526316,7533056.160
184,Vietnam,VNM,2010,0.103,VNM,2.0,LMC,1887.727320,86932500.0,10.842105,8954047.500
185,Yemen,YEM,2010,0.103,YEM,1.0,LIC,432.386104,27584213.0,10.842105,2841173.939

In [14]:
ppd_income_level_grouped = ppd_income_level.groupby('income_id_num').agg(
    {'population_population_number_of_people':'sum',
    'total_plastic_pd':'sum'})
ppd_income_level_grouped['avg_plastic_ppd'] = (ppd_income_level_grouped['total_plastic_pd']/\
                                              ppd_income_level_grouped['population_population_number_of_people'])
ppd_income_level_grouped

,population_population_number_of_people,total_plastic_pd,avg_plastic_ppd
income_id_num,,,
1.0,3.070820e+08,1.729112e+07,0.056308
2.0,4.965333e+09,4.653701e+08,0.093724
3.0,1.185157e+09,2.939997e+08,0.248068